algo = input('Digite algo: ')
print('O tipo primitivo desse valor eh ', type(algo))
print('So tem espacos? ', algo.isspace())
print('Eh um numero? ', algo.isnumeric())
print('Eh alfabetico? ', algo.isalpha())
print('Eh alfanumerico?', algo.isalnum())
print('Esta em maiusculas?', algo.isupper())
print('Esta em minusculas?', algo.islower())
print('Esta capitalizada?', algo.istitle())